name: Build and release ParaView

on: [push]

env:
  PARAVIEW_SUPERBUILD_DIR: ${{ github.workspace }}/build
  PARAVIEW_VERSION: 5.10.1

jobs:
  build-paraview:
    name: Build ParaView Superbuild
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout ParaView
      run: |
        git clone -b v${PARAVIEW_VERSION} --depth 1 --recursive https://gitlab.kitware.com/paraview/paraview-superbuild.git

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential libgl1-mesa-dev \
        libxt-dev python3-dev python3-numpy libopenmpi-dev libtbb-dev \
        ninja-build libosmesa6 libosmesa6-dev

    - name: Configure
      run: |
        mkdir $PARAVIEW_SUPERBUILD_DIR
        cd $PARAVIEW_SUPERBUILD_DIR
        cmake -GNinja -DPARAVIEW_BUILD_EDITION=CATALYST_RENDERING \
        -DENABLE_osmesa=ON -DUSE_SYSTEM_osmesa=ON -DUSE_SYSTEM_python3=ON \
        -DUSE_SYSTEM_mpi=ON -DUSE_SYSTEM_llvm=ON \
        -Dparaview_SOURCE_SELECTION=${PARAVIEW_VERSION} \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo $GITHUB_WORKSPACE/paraview-superbuild

    - name: Build
      run: ninja
      working-directory: ${{ env.PARAVIEW_SUPERBUILD_DIR }}

    - name: Package
      run: tar -czvf paraview-v${PARAVIEW_VERSION}.tar.gz .
      working-directory: ${{ env.PARAVIEW_SUPERBUILD_DIR }}/install

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: paraview-v${{ env.PARAVIEW_VERSION }}
        path: ${{ env.PARAVIEW_SUPERBUILD_DIR }}/paraview-v${{ env.PARAVIEW_VERSION }}.tar.gz

  release-paraview:
    needs: build-paraview
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: paraview-v${{ env.PARAVIEW_VERSION }}

      - name: Make release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "paraview-v${{ env.PARAVIEW_VERSION }}.tar.gz"



