name: Build and release ParaView

on: [push]

env:
  PARAVIEW_SUPERBUILD_DIR: ${{ github.workspace }}/build
  PARAVIEW_VERSION: 5.10.1

jobs:
  build-paraview:
    name: Build ParaView Superbuild
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout ParaView
        run: |
          git clone -b v${PARAVIEW_VERSION} --depth 1 --recursive https://gitlab.kitware.com/paraview/paraview-superbuild.git

      - name: Install dependencies
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
          sudo apt-get update
          sudo apt-get -y remove cmake cmake-*
          sudo apt-get -y install cmake=3.21.3-0kitware1ubuntu20.04.1
          sudo apt-get -y install build-essential libgl1-mesa-dev \
          libxt-dev python3-dev python3-numpy libopenmpi-dev libtbb-dev \
          ninja-build libosmesa6 libosmesa6-dev llvm-12-dev
          sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-12 12

      - name: Configure
        run: |
          mkdir $PARAVIEW_SUPERBUILD_DIR
          cd $PARAVIEW_SUPERBUILD_DIR
          cmake \
          -GNinja \
          -DPARAVIEW_BUILD_EDITION=CATALYST_RENDERING \
          -DENABLE_osmesa=ON \
          -DUSE_SYSTEM_osmesa=ON \
          -DENABLE_python3=ON \
          -DUSE_SYSTEM_python3=ON \
          -DENABLE_mpi=ON \
          -DUSE_SYSTEM_mpi=ON \
          -DENABLE_llvm=ON \
          -DUSE_SYSTEM_llvm=ON \
          -Dparaview_SOURCE_SELECTION=${PARAVIEW_VERSION} \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          $GITHUB_WORKSPACE/paraview-superbuild

      - name: Build
        run: ninja
        working-directory: ${{ env.PARAVIEW_SUPERBUILD_DIR }}

      - name: Test paraview-config
        run: |
          ./paraview-config --cppflags -v CommonDataModel -v PythonUsed
          ./paraview-config --ldflags -v CommonDataModel -v PythonUsed
          ./paraview-config --cppflags -c PythonCatalyst
          ./paraview-config --ldflags -c PythonCatalyst
        working-directory: ${{ env.PARAVIEW_SUPERBUILD_DIR }}/install/bin

      - name: Package
        run: tar -czvf paraview-v${PARAVIEW_VERSION}.tar.gz -C $PARAVIEW_SUPERBUILD_DIR/install .

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: paraview-v${{ env.PARAVIEW_VERSION }}
          path: paraview-v${{ env.PARAVIEW_VERSION }}.tar.gz
          if-no-files-found: error

  test-paraview-config:
    name: Test paraview-config
    needs: build-paraview
    runs-on: ubuntu-20.04

    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: paraview-v${{ env.PARAVIEW_VERSION }}

      - name: Untar
        run: |
          mkdir $PARAVIEW_SUPERBUILD_DIR/install
          cd $PARAVIEW_SUPERBUILD_DIR/install
          tar -xzvf $GITHUB_WORKSPACE/paraview-v${PARAVIEW_VERSION}.tar.gz

      - name: Install dependencies
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
           echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
          sudo apt-get update
          sudo apt-get -y remove cmake cmake-*
          sudo apt-get -y install cmake=3.21.3-0kitware1ubuntu20.04.1
          sudo apt-get -y install build-essential libgl1-mesa-dev \
          libxt-dev python3-dev python3-numpy libopenmpi-dev libtbb-dev \
          ninja-build libosmesa6 libosmesa6-dev llvm-12-dev
          sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-12 12

      - name: Test paraview-config
        run: |
          ./paraview-config --cppflags -v CommonDataModel -v PythonUsed
          ./paraview-config --ldflags -v CommonDataModel -v PythonUsed
          ./paraview-config --cppflags -c PythonCatalyst
          ./paraview-config --ldflags -c PythonCatalyst
        working-directory: ${{ env.PARAVIEW_SUPERBUILD_DIR }}/install/bin

